base_dir: ./log/gc_lstm/
data_dir: data/Beijing/
batch_size: 32
num_input_station: 10
target_station:
  - 房山
  - 天坛
  - 云岗
  - 东四环
  - 官园
  - 东四
  - 北部新区
  - 丰台花园
  - 古城
  - 南三环
input_features:
  - PM2.5
  - Mean
  - AQI
  - PM10
  - CO
  - NO2
  - O3
  - SO2
  - prec
  - lrad
  - shum
  - pres  
  - temp
  - wind
  - srad
target_features:
  - PM2.5
train_size: 0.6
valid_size: 0.25
test_size: 0.15

input_len: 24
output_len: 1
input_dim: 15
hidden_dim: 50
output_dim: 100
k: 2
num_conv_layers: 2
num_lstm_layers: 2
hidden_lstm_dim: 40
bidirect: True
dropout: 0.2

lr: 0.005
lr_decay_ratio: 0.5
optimizer: adam
patience: 10
epochs: 150
delta: 0
alpha: 0.1